'use strict';
const client=supabase.createClient('https://pgagpvfiplizahsnmvxf.supabase.co','sb_publishable_ZypHy48w_5CFqkjpuRYCbA_802_MDed',{auth:{storageKey:'dt-parent-sandbox-auth',persistSession:true,detectSessionInUrl:true}});
const $=id=>document.getElementById(id),endpoint='https://pgagpvfiplizahsnmvxf.supabase.co/functions/v1/parent-sandbox';
let state,card,submitting=false;
let setupRequested=new URLSearchParams(location.search).get('account-setup')==='1';
client.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){$('setup').hidden=false;}});
$('setup-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');if($('new-password').value!==$('confirm-password').value){$('setup-status').textContent='Those passwords do not match.';return;}button.disabled=true;try{const {error}=await client.auth.updateUser({password:$('new-password').value});if(error)throw error;$('new-password').value='';$('confirm-password').value='';$('setup-status').textContent='Test password saved.';$('setup-form').hidden=true;setupRequested=false;$('setup').hidden=true;history.replaceState(null,'',location.pathname);await refresh();}catch(e){$('setup-status').textContent=e.message;}finally{button.disabled=false;}});
async function api(body){const {data:{session}}=await client.auth.getSession();if(!session)throw new Error('Please sign in.');const response=await fetch(endpoint,{method:body?'POST':'GET',headers:{authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok)throw new Error(result.message||'Test service unavailable.');return result}
async function refresh(){try{const {data:{session}}=await client.auth.getSession();$('login').hidden=!!session;$('family').hidden=!session;if(!session)return;if(setupRequested)$('setup').hidden=false;state=await api();$('family-name').textContent=state.family.family_name;$('dancer-name').textContent=state.family.dancer_name;const paid=state.invoice.status==='paid'&&!!state.invoice.verified_event_id;$('balance').textContent=paid?'$0.00':'$1.00';$('invoice-status').textContent=paid?'Paid':state.invoice.status==='pending'?'Awaiting receipt':'Test only';$('open-payment').disabled=!state.enabled||state.invoice.status!=='ready';$('receipt').hidden=!paid;$('receipt-detail').textContent=paid?`$1.00 · Test card ending ${state.invoice.card_last_four||'—'} · ${new Date(state.invoice.paid_at).toLocaleString()}`:'';$('availability').textContent=!state.enabled?'Test payments are currently switched off.':state.invoice.status==='pending'?'A payment is already being checked. Refresh its status; do not start another payment.':'';$('status').textContent='';}catch(e){$('status').textContent=e.message;$('open-payment').disabled=true}}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const {error}=await client.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});$('password').value='';if(error)throw error;await refresh()}catch(e){$('status').textContent=e.message}finally{button.disabled=false}});
$('sign-out').onclick=async()=>{await client.auth.signOut();state=null;await refresh()};$('refresh').onclick=refresh;
async function loadSquare(){if(window.Square)return;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://sandbox.web.squarecdn.com/v1/square.js';script.onload=resolve;script.onerror=()=>reject(new Error('Test card form could not load.'));document.head.append(script)})}
$('open-payment').onclick=async()=>{try{await refresh();if(!state?.enabled||state.invoice.status!=='ready')return;$('checkout').showModal();$('consent').checked=false;$('submit-payment').disabled=true;$('payment-status').textContent='Loading test card form…';if(card)await card.destroy();await loadSquare();card=await Square.payments(state.applicationId,state.locationId).card();await card.attach('#square-card');$('payment-status').textContent='';}catch(e){$('payment-status').textContent=e.message}};
$('close-payment').onclick=()=>{if(!submitting)$('checkout').close()};$('checkout').addEventListener('cancel',e=>{if(submitting)e.preventDefault()});
$('consent').onchange=()=>{$('submit-payment').disabled=submitting||!card||!$('consent').checked||state?.invoice.status!=='ready'};
$('submit-payment').onclick=async()=>{if(submitting||!$('consent').checked||!card)return;submitting=true;$('submit-payment').disabled=true;$('close-payment').disabled=true;try{$('payment-status').textContent='Submitting test payment…';const token=await card.tokenize();if(token.status!=='OK'||!token.token)throw new Error('Check the test card details.');await api({invoiceId:state.invoice.id,sourceToken:token.token});for(let n=0;n<8;n++){await refresh();if(state.invoice.status==='paid'&&state.invoice.verified_event_id){$('payment-status').textContent='Payment received and verified. Your test balance is $0.00.';return}await new Promise(r=>setTimeout(r,1250))}$('payment-status').textContent='Payment submitted. Receipt verification is pending. Close this window and refresh the payment status; do not submit again.'}catch(e){$('payment-status').textContent=e.message+' Close this window and refresh the status before continuing.'}finally{submitting=false;$('close-payment').disabled=false;await refresh()}};
void refresh();
