(() => {
  const KEY="dt-director-duet-identity",names={lexi:"Lexi",tiffany:"Ms. Tiffany"};let messages=[],channel=null,ready=false;
  const $=s=>document.querySelector(s),tour=()=>document.body.dataset.tourMode==="true"||new URLSearchParams(location.search).get("tour")==="1",who=()=>localStorage.getItem(KEY)||"tiffany",safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  function build(){const host=$("#tulle-root");if(!host)return false;const existing=$("#director-duet");if(existing){if(existing.parentElement!==host)host.appendChild(existing);return true}const root=document.createElement("div");root.id="director-duet";root.className="director-duet-root";root.dataset.unsavedIgnore="true";root.innerHTML=`<button class="director-duet-launcher" type="button" aria-label="Open Admin Chat" aria-expanded="false"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3h11A2.5 2.5 0 0 1 20 5.5v8a2.5 2.5 0 0 1-2.5 2.5H10l-5 4v-4.7A2.5 2.5 0 0 1 4 13.5z"></path><path d="M8 8h8M8 12h5"></path></svg></button><section class="director-duet" role="dialog" aria-modal="false" aria-labelledby="director-duet-title" hidden><div class="director-duet-head"><div><h3 id="director-duet-title">Admin Chat</h3><p>Lexi + Ms. Tiffany</p></div><button class="director-duet-close" type="button" aria-label="Close Admin Chat">×</button></div><label class="director-duet-identity">This device is <select id="director-duet-identity"><option value="lexi">Lexi</option><option value="tiffany">Ms. Tiffany</option></select></label><div class="director-duet-messages" id="director-duet-messages" aria-live="polite"><p class="director-duet-empty">Connecting…</p></div><form class="director-duet-composer" id="director-duet-form"><textarea id="director-duet-draft" maxlength="2000" aria-label="Admin Chat message" required></textarea><button class="primary" type="submit">Send</button></form><p class="director-duet-status" id="director-duet-status" role="status"></p></section>`;host.appendChild(root);root.querySelector(".director-duet-launcher").onclick=()=>toggle(true);root.querySelector(".director-duet-close").onclick=()=>toggle(false);root.querySelector("#director-duet-identity").onchange=e=>{const value=e.target.value==="lexi"?"lexi":"tiffany";localStorage.setItem(KEY,value);render();status(`This device now sends as ${names[value]}.`)};root.querySelector("#director-duet-form").onsubmit=submit;return true}
  function toggle(open){const panel=$("#director-duet .director-duet"),button=$("#director-duet .director-duet-launcher");if(!panel||!button)return;panel.hidden=!open;button.setAttribute("aria-expanded",String(open));if(open){render();$("#director-duet-draft")?.focus()}}
  function render(){const list=$("#director-duet-messages"),select=$("#director-duet-identity"),draft=$("#director-duet-draft");if(!list||!select)return;select.value=who();if(draft)draft.placeholder=`Message ${who()==="lexi"?"Ms. Tiffany":"Lexi"}`;list.innerHTML=messages.length?messages.map(m=>`<article class="director-duet-message sender-${safe(m.sender_key)} ${m.sender_key===who()?"mine":""}"><strong>${safe(m.sender_name)}</strong><span>${safe(m.body)}</span><time>${safe(new Date(m.created_at).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"}))}</time></article>`).join(""):'<p class="director-duet-empty">No messages yet. Say hello!</p>';requestAnimationFrame(()=>list.scrollTop=list.scrollHeight)}
  function status(text){const node=$("#director-duet-status");if(node)node.textContent=text}
  async function load(){if(tour()){ready=true;render();status("Preview chat · messages are not saved in tour mode.");return}if(!window.dtSupabase||!window.dtCurrentProfile)return;const{data,error}=await window.dtSupabase.from("director_device_chat_messages").select("id, sender_key, sender_name, body, created_at").order("created_at",{ascending:true}).limit(500);if(error){ready=false;status("Director chat could not connect. Refresh and try again.");console.error("Director chat could not load",error);return}messages=data||[];ready=true;status("Live · messages update automatically on both computers.");render()}
  function subscribe(){if(tour()||channel||!window.dtSupabase||!window.dtCurrentProfile)return;channel=window.dtSupabase.channel("director-device-chat").on("postgres_changes",{event:"INSERT",schema:"public",table:"director_device_chat_messages"},()=>load()).subscribe()}
  async function send(body){if(tour()){messages.push({id:crypto.randomUUID(),sender_key:who(),sender_name:names[who()],body,created_at:new Date().toISOString()});render();return true}if(!ready||!window.dtSupabase){status("Director chat is reconnecting. Refresh and try again.");return false}const{error}=await window.dtSupabase.rpc("post_director_device_chat_message",{device_sender_key:who(),message_body:body});if(error){console.error("Director chat message could not send",error);status("That message did not send. Please try again.");return false}await load();return true}
  async function submit(event){event.preventDefault();const draft=$("#director-duet-draft"),text=draft?.value.trim()||"",button=event.currentTarget.querySelector("button");if(!text)return;button.disabled=true;const sent=await send(text);button.disabled=false;if(sent&&draft)draft.value=""}
  function init(profile=window.dtCurrentProfile){if(!build()){setTimeout(()=>init(profile),50);return}const root=$("#director-duet");if(!tour()&&!["admin","director"].includes(profile?.role)){root.hidden=true;return}root.hidden=false;if(!localStorage.getItem(KEY))localStorage.setItem(KEY,"tiffany");render();void load();subscribe()}
  window.addEventListener("dt-auth-ready",event=>init(event.detail?.profile));init();
})();
